In [1]:
%cd ..

/home/jovyan/work


In [2]:
from functions.functions import TestClass
import numpy as np

S = np.zeros((4,4), dtype=np.float64, order='F')

t = TestClass()

print(t.testOpenMP(S))

[[-0.09041179  1.8089189  -1.43358978 -1.45107369]
 [ 0.5154837   1.66478027  0.42787551  1.21670702]
 [-0.54086211  0.54284691 -1.93479771 -1.37328364]
 [ 0.05360364  0.86918772 -1.02845292 -0.39622242]]


In [3]:
from functions.functions import TestClass
import numpy as np

S = np.zeros((4,4), dtype=np.float64, order='F')

t = TestClass()

print(t.testBLAS(S))

[[-0.72167372  0.10558346  0.7123016   0.84091491]
 [-1.89128371  0.52541952 -0.01900249 -0.07754618]
 [ 0.87102625 -0.37790888 -0.97731532 -0.79063836]
 [ 0.38206656  1.06700087 -0.94940136  0.10941543]]


In [6]:
from functions.functions import TestClass
import numpy as np

S = np.array([[1, 0, 0], [0, 2, 0], [0, 0, 3]])
v = np.array([1,4,9])

t = TestClass()

print(t.testLAPACK(S, v))

TypeError: 'list' object cannot be interpreted as an integer