In [1]:
%cd ..

/home/jovyan/work


In [2]:
from functions.functions import TestClass
import numpy as np

S = np.zeros((4,4), dtype=np.float64, order='F')

t = TestClass()

print(t.testOpenMP(S))

[[-0.09041179  1.8089189  -1.43358978 -1.45107369]
 [ 0.5154837   1.66478027  0.42787551  1.21670702]
 [-0.54086211  0.54284691 -1.93479771 -1.37328364]
 [ 0.05360364  0.86918772 -1.02845292 -0.39622242]]


In [ ]:
from functions.functions import TestClass
import numpy as np

S = np.zeros((4,4), dtype=np.float64, order='F')

t = TestClass()

print(t.testBLAS(S))