In [1]:
%cd ..

/home/jovyan/work


In [11]:
from functions.functions import TestClass
import numpy as np

S = np.zeros((4,4), dtype=np.float64, order='F')

t = TestClass()

print(t.testOpenMP(S))

[[ 1.56093041 -0.16919305  1.60883229 -0.49917209]
 [-0.60442826 -1.74761665  1.40367915  1.04099495]
 [-1.74331472 -1.04688018 -0.933337    0.05014146]
 [-1.9199078   1.88253653  0.15904136  0.67089504]]
